services:
  alias:
    profiles:
      - in-memory
      - mongodb
    container_name: alias
    image: ${ALIAS_IMAGE_NAME:-alias:1.0.0}
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-pass}
      MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE:-admin}
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./config/config.docker.yaml:/etc/alias/config.yaml
    networks:
      - aliasnet

  mongodb:
    profiles:
      - mongodb
    image: mongo:7.0.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
      MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE:-admin}
      MONGO_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-pass}
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./migrations/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - aliasnet

  alias-client:
    profiles:
      - client
    image: ${ALIAS_IMAGE_NAME:-alias:1.0.0}
    entrypoint: /bin/alias-client
    container_name: alias-client
    expose:
      - 8081:8081
    command:
      - --address=alias:8081
      - --message=let me look for ya with http://www.ya.ru or http://www.google.com.
    networks:
      - aliasnet

networks:
  aliasnet:
    driver: bridge