service:
  http: alias:8080
  grpc: alias:8081
  grpc-gateway: alias:8082
storage:
  type: mongodb # in-memory | mongodb
  config:
    uri: mongodb://mongodb:27017
    database: appdb

logger:
  level: info
  encoding: console