service:
  http: localhost:8080
  grpc: localhost:8081
  grpc-gateway: localhost:8082
  base-url: http://localhost:8080
storage:
  type: mongodb # in-memory | mongodb
  config:
    uri: mongodb://localhost:27017
    database: appdb
producers:
  - name: "Alias Used Event Producer"
    topic: "used"
    brokers:
        - name: "kafka"
          type: "kafka"
          URI: "localhost:9092"
  - name: "Alias Expired Event Producer"
    topic: "expired"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "localhost:9092"

consumers:
  - name: "Alias Used Event Consumer"
    group_id: "used_q"
    topic: "used"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "localhost:9092"
  - name: "Alias Expired Event Consumer"
    group_id: "expired_q"
    topic: "expired"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "localhost:9092"
logger:
  level: info
  encoding: console