service:
  http: alias:8080
  grpc: alias:8081
  grpc-gateway: alias:8082
  base-url: http://localhost:8080
storage:
  type: mongodb # in-memory | mongodb
  config:
    uri: mongodb://mongodb:27017
    database: appdb
producers:
  - name: "Alias Used Event Producer"
    topic: "used"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "kafka:29092"
  - name: "Alias Expired Event Producer"
    topic: "expired"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "kafka:29092"

consumers:
  - name: "Alias Used Event Consumer"
    group_id: "used_q"
    topic: "used"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "kafka:29092"
  - name: "Alias Expired Event Consumer"
    group_id: "expired_q"
    topic: "expired"
    brokers:
      - name: "kafka"
        type: "kafka"
        URI: "kafka:29092"
logger:
  level: info
  encoding: console